--database: CSC498.db
CREATE TABLE raw AS
SELECT * FROM final;

DROP TABLE final;
CREATE TABLE final AS
SELECT * FROM raw;

CREATE TABLE final_new AS
SELECT 
    f.SEX, f.AGE, f.MARST, f.INCWAGE, f.VETSTAT, 
    f.HISPAN, f.CITIZEN, f.SPEAKENG,
    e.EDUC, e.EDUCYEARS,
    d1.DEGFIELD AS DEGFIELD1, d2.DEGFIELD AS DEGFIELD2,
    o.OCC,
    i.IND,
    r.RACE, 
    s.WORKSTATE
FROM final f
LEFT JOIN education e ON f.EDUC = e.EDUCID
LEFT JOIN degree d1 ON f.DEGFIELD = d1.DEGFIELDID
LEFT JOIN degree d2 ON f.DEGFIELD2 = d2.DEGFIELDID
LEFT JOIN occupation o ON f.OCC = o.OCCID
LEFT JOIN industry i ON f.IND = i.INDID
LEFT JOIN race r ON f.RACE = r.RACEID
LEFT JOIN state s ON f.PWSTATE2 = s.PWSTATE2;

DROP TABLE final;

ALTER TABLE final_new RENAME TO final;

UPDATE final
SET SEX = CASE WHEN SEX = 2 THEN 0 ELSE 1 END,
    MARST = CASE WHEN MARST < 3 THEN 1 ELSE 0 END,
    VETSTAT = CASE WHEN VETSTAT = 2 THEN 0 ELSE 1 END,
    HISPAN = CASE WHEN HISPAN > 0 THEN 1 ELSE 0 END,
    CITIZEN = CASE WHEN CITIZEN < 3 THEN 1 ELSE 0 END,
    SPEAKENG = CASE WHEN SPEAKENG = 1 THEN 0 ELSE 1 END;

DELETE FROM final
WHERE CAST(INCWAGE AS INTEGER) < 15000 OR CAST(INCWAGE AS INTEGER) > 500000;

SELECT COUNT(*) FROM final; -- 1,344,740
